version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependency
    schedule:
      interval: monthly
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
      github-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
